import type { UserPreferredLanguage } from "../domain/types";

export const languageOptions: Array<{ value: UserPreferredLanguage; label: string }> = [
  { value: "fr", label: "Francais" },
  { value: "en", label: "English" },
  { value: "de", label: "Deutsch" },
  { value: "it", label: "Italiano" },
  { value: "es", label: "Espanol" }
];

export function getLanguageLabel(language: UserPreferredLanguage): string {
  return languageOptions.find((item) => item.value === language)?.label || language;
}

export function hasConfiguredLanguage(value?: string): value is UserPreferredLanguage {
  return languageOptions.some((item) => item.value === value);
}

export type TranslationKey = keyof typeof translations.fr;

export const translations = {
  fr: {
    appName: "Polaris CVC",
    loadingTitle: "Connexion en cours",
    loadingText: "Verification de votre session securisee.",
    loginTitle: "Connexion securisee",
    loginText: "Connectez-vous avec votre compte Google autorise pour acceder a Polaris.",
    firebaseReady: "Firebase est configure.",
    firebaseMissing: "Firebase n'est pas configure.",
    continueGoogle: "Continuer avec Google",
    signingIn: "Connexion...",
    languageTitle: "Langue de travail",
    languageIntro: "Choisissez la langue de l'interface et des futurs diagnostics.",
    saving: "Enregistrement...",
    dashboard: "Tableau de bord",
    welcome: "Bienvenue dans Polaris CVC",
    dashboardIntro: "Pilotez les interventions, la documentation technique et l'identification terrain depuis un seul espace.",
    diagnostic: "Diagnostic",
    diagnosticNew: "Diagnostic",
    diagnosticsArchive: "Archives",
    interventionNew: "Nouvelle intervention",
    interventions: "Interventions",
    interventionCurrent: "En cours",
    identifyEquipment: "Identifier un equipement",
    documents: "Bibliotheque technique",
    users: "Utilisateurs",
    settings: "Parametres",
    about: "A propos",
    aboutText: "Logiciel professionnel de diagnostic, intervention et documentation CVC.",
    ai: "IA",
    aiSettingsText: "Service IA securise cote serveur.",
    storage: "Stockage",
    firestoreActive: "Firestore actif",
    localMode: "Mode local",
    profile: "Profil",
    company: "Entreprise",
    signOut: "Se deconnecter",
    recentActivity: "Activite recente",
    noRecentActivity: "Aucune activite recente",
    noRecentActivityText: "Les dernieres actions reelles apparaitront ici.",
    openInterventions: "Interventions ouvertes",
    completedInterventions: "Interventions terminees",
    identifiedEquipment: "Equipements identifies",
    technicalDocuments: "Documents techniques",
    favorites: "Favoris",
    noDiagnosticArchive: "Aucun diagnostic archive",
    noDiagnosticArchiveText: "Les diagnostics termines apparaitront ici automatiquement.",
    noDocument: "Aucun document disponible",
    noAdditionalUser: "Aucun utilisateur supplementaire",
    noIntervention: "Aucune intervention",
    noCurrentIntervention: "Aucune intervention en cours.",
    realDataWillAppear: "Les donnees reelles apparaitront ici des qu'elles seront disponibles.",
    search: "Rechercher",
    photoPlate: "Prenez une photo de la plaque signaletique",
    photoFault: "Prenez une photo du defaut ou du code erreur",
    extraPhotos: "Photos supplementaires",
    photoMinimum: "Ajoutez au moins une photo",
    singlePhotoPrecisionHint: "Vous pouvez lancer l'analyse avec cette photo. Ajouter une photo de la plaque signaletique ou du defaut peut ameliorer la precision.",
    multiplePhotoPrecisionHint: "Toutes les photos ajoutees seront analysees. La plaque signaletique et le defaut ameliorent la precision lorsqu'ils sont disponibles.",
    recommendedAdditionalPhotos: "Photos complementaires recommandees",
    photo: "Photo",
    gallery: "Galerie",
    remove: "Supprimer",
    noPhoto: "Aucune photo ajoutee.",
    aiUnavailable: "Analyse IA indisponible tant que le backend securise n'est pas configure.",
    aiUnavailableShort: "Analyse IA indisponible",
    finishDiagnostic: "Terminer le diagnostic",
    captureOnly: "Vous pouvez preparer les photos du dossier, mais aucun diagnostic automatique ne sera genere.",
    library: "Bibliotheque",
    folderImport: "Import de dossier",
    selectFolder: "Selectionner un dossier de PDF et images",
    unavailableIdentification: "Identification non connectee",
    noEquipmentIdentified: "Aucun equipement identifie",
    notProvided: "Non renseigne"
  },
  en: {
    appName: "Polaris CVC",
    loadingTitle: "Signing in",
    loadingText: "Checking your secure session.",
    loginTitle: "Secure sign-in",
    loginText: "Sign in with your authorized Google account to access Polaris.",
    firebaseReady: "Firebase is configured.",
    firebaseMissing: "Firebase is not configured.",
    continueGoogle: "Continue with Google",
    signingIn: "Signing in...",
    languageTitle: "Working language",
    languageIntro: "Choose the language for the interface and future diagnostics.",
    saving: "Saving...",
    dashboard: "Dashboard",
    welcome: "Welcome to Polaris CVC",
    dashboardIntro: "Manage interventions, technical documentation and field identification from one workspace.",
    diagnostic: "Diagnostic",
    diagnosticNew: "Diagnostic",
    diagnosticsArchive: "Archives",
    interventionNew: "New intervention",
    interventions: "Interventions",
    interventionCurrent: "In progress",
    identifyEquipment: "Identify equipment",
    documents: "Technical library",
    users: "Users",
    settings: "Settings",
    about: "About",
    aboutText: "Professional HVAC diagnostic, intervention and documentation software.",
    ai: "AI",
    aiSettingsText: "Secure server-side AI service.",
    storage: "Storage",
    firestoreActive: "Firestore active",
    localMode: "Local mode",
    profile: "Profile",
    company: "Company",
    signOut: "Sign out",
    recentActivity: "Recent activity",
    noRecentActivity: "No recent activity",
    noRecentActivityText: "Real activity will appear here.",
    openInterventions: "Open interventions",
    completedInterventions: "Completed interventions",
    identifiedEquipment: "Identified equipment",
    technicalDocuments: "Technical documents",
    favorites: "Favorites",
    noDiagnosticArchive: "No archived diagnostic",
    noDiagnosticArchiveText: "Completed diagnostics will appear here automatically.",
    noDocument: "No document available",
    noAdditionalUser: "No additional user",
    noIntervention: "No intervention",
    noCurrentIntervention: "No intervention in progress.",
    realDataWillAppear: "Real data will appear here as soon as it is available.",
    search: "Search",
    photoPlate: "Take a photo of the nameplate",
    photoFault: "Take a photo of the fault or error code",
    extraPhotos: "Additional photos",
    photoMinimum: "Add at least one photo",
    singlePhotoPrecisionHint: "You can start the analysis with this photo. Adding a nameplate or fault photo can improve accuracy.",
    multiplePhotoPrecisionHint: "All added photos will be analyzed. The nameplate and fault view improve accuracy when available.",
    recommendedAdditionalPhotos: "Recommended additional photos",
    photo: "Photo",
    gallery: "Gallery",
    remove: "Remove",
    noPhoto: "No photo added.",
    aiUnavailable: "AI analysis is unavailable until the secure backend is configured.",
    aiUnavailableShort: "AI analysis unavailable",
    finishDiagnostic: "Finish diagnostic",
    captureOnly: "You can prepare the case photos, but no automatic diagnostic will be generated.",
    library: "Library",
    folderImport: "Folder import",
    selectFolder: "Select a folder of PDFs and images",
    unavailableIdentification: "Identification not connected",
    noEquipmentIdentified: "No equipment identified",
    notProvided: "Not provided"
  },
  de: {
    appName: "Polaris CVC",
    loadingTitle: "Anmeldung laeuft",
    loadingText: "Sichere Sitzung wird geprueft.",
    loginTitle: "Sichere Anmeldung",
    loginText: "Melden Sie sich mit Ihrem autorisierten Google-Konto an.",
    firebaseReady: "Firebase ist konfiguriert.",
    firebaseMissing: "Firebase ist nicht konfiguriert.",
    continueGoogle: "Mit Google fortfahren",
    signingIn: "Anmeldung...",
    languageTitle: "Arbeitssprache",
    languageIntro: "Waehlen Sie die Sprache fuer Oberflaeche und kuenftige Diagnosen.",
    saving: "Speichern...",
    dashboard: "Uebersicht",
    welcome: "Willkommen bei Polaris CVC",
    dashboardIntro: "Verwalten Sie Einsaetze, technische Dokumente und Feldidentifikation.",
    diagnostic: "Diagnose",
    diagnosticNew: "Diagnose",
    diagnosticsArchive: "Archive",
    interventionNew: "Neuer Einsatz",
    interventions: "Einsaetze",
    interventionCurrent: "Laufend",
    identifyEquipment: "Geraet identifizieren",
    documents: "Technische Bibliothek",
    users: "Benutzer",
    settings: "Einstellungen",
    about: "Info",
    aboutText: "Professionelle Software fuer CVC-Diagnose, Einsaetze und Dokumentation.",
    ai: "KI",
    aiSettingsText: "Sicherer serverseitiger KI-Dienst.",
    storage: "Speicher",
    firestoreActive: "Firestore aktiv",
    localMode: "Lokaler Modus",
    profile: "Profil",
    company: "Unternehmen",
    signOut: "Abmelden",
    recentActivity: "Letzte Aktivitaet",
    noRecentActivity: "Keine letzte Aktivitaet",
    noRecentActivityText: "Echte Aktivitaeten erscheinen hier.",
    openInterventions: "Offene Einsaetze",
    completedInterventions: "Abgeschlossene Einsaetze",
    identifiedEquipment: "Identifizierte Geraete",
    technicalDocuments: "Technische Dokumente",
    favorites: "Favoriten",
    noDiagnosticArchive: "Keine archivierte Diagnose",
    noDiagnosticArchiveText: "Abgeschlossene Diagnosen erscheinen hier automatisch.",
    noDocument: "Kein Dokument verfuegbar",
    noAdditionalUser: "Kein weiterer Benutzer",
    noIntervention: "Kein Einsatz",
    noCurrentIntervention: "Kein laufender Einsatz.",
    realDataWillAppear: "Echte Daten erscheinen hier, sobald sie verfuegbar sind.",
    search: "Suchen",
    photoPlate: "Foto des Typenschilds aufnehmen",
    photoFault: "Foto des Fehlers oder Fehlercodes aufnehmen",
    extraPhotos: "Weitere Fotos",
    photoMinimum: "Mindestens ein Foto hinzufuegen",
    singlePhotoPrecisionHint: "Sie koennen die Analyse mit diesem Foto starten. Ein Foto des Typenschilds oder Fehlers kann die Genauigkeit verbessern.",
    multiplePhotoPrecisionHint: "Alle hinzugefuegten Fotos werden analysiert. Typenschild und Fehleransicht verbessern die Genauigkeit, wenn vorhanden.",
    recommendedAdditionalPhotos: "Empfohlene weitere Fotos",
    photo: "Foto",
    gallery: "Galerie",
    remove: "Entfernen",
    noPhoto: "Kein Foto hinzugefuegt.",
    aiUnavailable: "KI-Analyse ist nicht verfuegbar, bis das sichere Backend konfiguriert ist.",
    aiUnavailableShort: "KI-Analyse nicht verfuegbar",
    finishDiagnostic: "Diagnose abschliessen",
    captureOnly: "Sie koennen Fotos vorbereiten, aber keine automatische Diagnose wird erstellt.",
    library: "Bibliothek",
    folderImport: "Ordnerimport",
    selectFolder: "Ordner mit PDFs und Bildern auswaehlen",
    unavailableIdentification: "Identifikation nicht verbunden",
    noEquipmentIdentified: "Kein Geraet identifiziert",
    notProvided: "Nicht angegeben"
  },
  it: {
    appName: "Polaris CVC",
    loadingTitle: "Accesso in corso",
    loadingText: "Verifica della sessione sicura.",
    loginTitle: "Accesso sicuro",
    loginText: "Accedi con il tuo account Google autorizzato.",
    firebaseReady: "Firebase e configurato.",
    firebaseMissing: "Firebase non e configurato.",
    continueGoogle: "Continua con Google",
    signingIn: "Accesso...",
    languageTitle: "Lingua di lavoro",
    languageIntro: "Scegli la lingua dell'interfaccia e delle diagnosi future.",
    saving: "Salvataggio...",
    dashboard: "Cruscotto",
    welcome: "Benvenuto in Polaris CVC",
    dashboardIntro: "Gestisci interventi, documentazione tecnica e identificazione sul campo.",
    diagnostic: "Diagnosi",
    diagnosticNew: "Diagnosi",
    diagnosticsArchive: "Archivio",
    interventionNew: "Nuovo intervento",
    interventions: "Interventi",
    interventionCurrent: "In corso",
    identifyEquipment: "Identifica apparecchiatura",
    documents: "Biblioteca tecnica",
    users: "Utenti",
    settings: "Impostazioni",
    about: "Informazioni",
    aboutText: "Software professionale per diagnosi, interventi e documentazione CVC.",
    ai: "IA",
    aiSettingsText: "Servizio IA sicuro lato server.",
    storage: "Archiviazione",
    firestoreActive: "Firestore attivo",
    localMode: "Modalita locale",
    profile: "Profilo",
    company: "Azienda",
    signOut: "Disconnetti",
    recentActivity: "Attivita recente",
    noRecentActivity: "Nessuna attivita recente",
    noRecentActivityText: "Le attivita reali appariranno qui.",
    openInterventions: "Interventi aperti",
    completedInterventions: "Interventi completati",
    identifiedEquipment: "Apparecchiature identificate",
    technicalDocuments: "Documenti tecnici",
    favorites: "Preferiti",
    noDiagnosticArchive: "Nessuna diagnosi archiviata",
    noDiagnosticArchiveText: "Le diagnosi completate appariranno qui automaticamente.",
    noDocument: "Nessun documento disponibile",
    noAdditionalUser: "Nessun utente aggiuntivo",
    noIntervention: "Nessun intervento",
    noCurrentIntervention: "Nessun intervento in corso.",
    realDataWillAppear: "I dati reali appariranno qui quando disponibili.",
    search: "Cerca",
    photoPlate: "Scatta una foto della targhetta",
    photoFault: "Scatta una foto del guasto o codice errore",
    extraPhotos: "Foto aggiuntive",
    photoMinimum: "Aggiungi almeno una foto",
    singlePhotoPrecisionHint: "Puoi avviare l'analisi con questa foto. Aggiungere una foto della targhetta o del guasto puo migliorare la precisione.",
    multiplePhotoPrecisionHint: "Tutte le foto aggiunte verranno analizzate. Targhetta e vista del guasto migliorano la precisione quando disponibili.",
    recommendedAdditionalPhotos: "Foto aggiuntive consigliate",
    photo: "Foto",
    gallery: "Galleria",
    remove: "Rimuovi",
    noPhoto: "Nessuna foto aggiunta.",
    aiUnavailable: "L'analisi IA non e disponibile finche il backend sicuro non e configurato.",
    aiUnavailableShort: "Analisi IA non disponibile",
    finishDiagnostic: "Termina diagnosi",
    captureOnly: "Puoi preparare le foto del caso, ma non verra generata alcuna diagnosi automatica.",
    library: "Biblioteca",
    folderImport: "Importazione cartella",
    selectFolder: "Seleziona una cartella di PDF e immagini",
    unavailableIdentification: "Identificazione non connessa",
    noEquipmentIdentified: "Nessuna apparecchiatura identificata",
    notProvided: "Non indicato"
  },
  es: {
    appName: "Polaris CVC",
    loadingTitle: "Iniciando sesion",
    loadingText: "Verificando la sesion segura.",
    loginTitle: "Inicio de sesion seguro",
    loginText: "Inicia sesion con tu cuenta Google autorizada.",
    firebaseReady: "Firebase esta configurado.",
    firebaseMissing: "Firebase no esta configurado.",
    continueGoogle: "Continuar con Google",
    signingIn: "Conectando...",
    languageTitle: "Idioma de trabajo",
    languageIntro: "Elige el idioma de la interfaz y de los diagnosticos futuros.",
    saving: "Guardando...",
    dashboard: "Panel",
    welcome: "Bienvenido a Polaris CVC",
    dashboardIntro: "Gestiona intervenciones, documentacion tecnica e identificacion en campo.",
    diagnostic: "Diagnostico",
    diagnosticNew: "Diagnostico",
    diagnosticsArchive: "Archivos",
    interventionNew: "Nueva intervencion",
    interventions: "Intervenciones",
    interventionCurrent: "En curso",
    identifyEquipment: "Identificar equipo",
    documents: "Biblioteca tecnica",
    users: "Usuarios",
    settings: "Ajustes",
    about: "Acerca de",
    aboutText: "Software profesional de diagnostico, intervencion y documentacion CVC.",
    ai: "IA",
    aiSettingsText: "Servicio IA seguro del lado del servidor.",
    storage: "Almacenamiento",
    firestoreActive: "Firestore activo",
    localMode: "Modo local",
    profile: "Perfil",
    company: "Empresa",
    signOut: "Cerrar sesion",
    recentActivity: "Actividad reciente",
    noRecentActivity: "Sin actividad reciente",
    noRecentActivityText: "La actividad real aparecera aqui.",
    openInterventions: "Intervenciones abiertas",
    completedInterventions: "Intervenciones completadas",
    identifiedEquipment: "Equipos identificados",
    technicalDocuments: "Documentos tecnicos",
    favorites: "Favoritos",
    noDiagnosticArchive: "Ningun diagnostico archivado",
    noDiagnosticArchiveText: "Los diagnosticos terminados apareceran aqui automaticamente.",
    noDocument: "Ningun documento disponible",
    noAdditionalUser: "Ningun usuario adicional",
    noIntervention: "Ninguna intervencion",
    noCurrentIntervention: "Ninguna intervencion en curso.",
    realDataWillAppear: "Los datos reales apareceran aqui cuando esten disponibles.",
    search: "Buscar",
    photoPlate: "Toma una foto de la placa",
    photoFault: "Toma una foto del fallo o codigo de error",
    extraPhotos: "Fotos adicionales",
    photoMinimum: "Anade al menos una foto",
    singlePhotoPrecisionHint: "Puedes iniciar el analisis con esta foto. Anadir una foto de la placa o del fallo puede mejorar la precision.",
    multiplePhotoPrecisionHint: "Se analizaran todas las fotos anadidas. La placa y la vista del fallo mejoran la precision cuando estan disponibles.",
    recommendedAdditionalPhotos: "Fotos adicionales recomendadas",
    photo: "Foto",
    gallery: "Galeria",
    remove: "Eliminar",
    noPhoto: "No se ha anadido ninguna foto.",
    aiUnavailable: "El analisis IA no esta disponible hasta configurar el backend seguro.",
    aiUnavailableShort: "Analisis IA no disponible",
    finishDiagnostic: "Finalizar diagnostico",
    captureOnly: "Puedes preparar las fotos del caso, pero no se generara ningun diagnostico automatico.",
    library: "Biblioteca",
    folderImport: "Importar carpeta",
    selectFolder: "Seleccionar una carpeta de PDF e imagenes",
    unavailableIdentification: "Identificacion no conectada",
    noEquipmentIdentified: "Ningun equipo identificado",
    notProvided: "No indicado"
  }
} satisfies Record<UserPreferredLanguage, Record<string, string>>;

export function translate(language: UserPreferredLanguage | undefined, key: TranslationKey): string {
  const selected = hasConfiguredLanguage(language) ? language : "fr";
  return translations[selected][key] || translations.en[key] || translations.fr[key] || key;
}

export function createTranslator(language: UserPreferredLanguage | undefined): (key: TranslationKey) => string {
  return (key) => translate(language, key);
}
